[profile.default]
src = "src"
helpers = "helpers"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-06/=lib/openzeppelin-contracts-06/",
    "openzeppelin-contracts-08/=lib/openzeppelin-contracts-08/contracts/",
]

eth_rpc_url = 'https://rpc.sepolia.org'
# eth_rpc_url = 'https://rpc.ankr.com/eth_sepolia'
etherscan_api_key = '${ETHERSCAN_KEY}'